/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FundamentalData {
  'eps' : number,
  'peRatio' : number,
  'marketCap' : bigint,
  'debtToEquity' : number,
  'revenueGrowth' : number,
  'dividendYield' : number,
}
export interface NewsItem {
  'title' : string,
  'content' : string,
  'source' : string,
  'impactScore' : bigint,
  'sentiment' : string,
  'timestamp' : Time,
}
export interface PriceData {
  'low' : number,
  'date' : Time,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : bigint,
}
export interface Recommendation {
  'confidenceScore' : bigint,
  'signal' : string,
}
export interface StockData {
  'ticker' : string,
  'name' : string,
  'news' : Array<NewsItem>,
  'lastUpdated' : Time,
  'fundamentalData' : FundamentalData,
  'historicalPrices' : Array<PriceData>,
  'recommendation' : Recommendation,
  'technicalIndicators' : TechnicalIndicators,
}
export interface TechnicalIndicators {
  'ma20' : number,
  'ma50' : number,
  'macd' : number,
  'bollingerLower' : number,
  'bollingerUpper' : number,
  'volumeTrend' : number,
  'rsi14' : number,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getAllRecommendations' : ActorMethod<[], Array<[string, Recommendation]>>,
  'getAllStockTickers' : ActorMethod<[], Array<string>>,
  'getFundamentalData' : ActorMethod<[string], [] | [FundamentalData]>,
  'getHistoricalPrices' : ActorMethod<[string], [] | [Array<PriceData>]>,
  'getNews' : ActorMethod<[string], [] | [Array<NewsItem>]>,
  'getRecommendationV2' : ActorMethod<[string], [] | [Recommendation]>,
  'getStock' : ActorMethod<[string], [] | [StockData]>,
  'getTechnicalIndicators' : ActorMethod<[string], [] | [TechnicalIndicators]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];