/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Recommendation = IDL.Record({
  'confidenceScore' : IDL.Nat,
  'signal' : IDL.Text,
});
export const FundamentalData = IDL.Record({
  'eps' : IDL.Float64,
  'peRatio' : IDL.Float64,
  'marketCap' : IDL.Nat,
  'debtToEquity' : IDL.Float64,
  'revenueGrowth' : IDL.Float64,
  'dividendYield' : IDL.Float64,
});
export const Time = IDL.Int;
export const PriceData = IDL.Record({
  'low' : IDL.Float64,
  'date' : Time,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Nat,
});
export const NewsItem = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'source' : IDL.Text,
  'impactScore' : IDL.Nat,
  'sentiment' : IDL.Text,
  'timestamp' : Time,
});
export const TechnicalIndicators = IDL.Record({
  'ma20' : IDL.Float64,
  'ma50' : IDL.Float64,
  'macd' : IDL.Float64,
  'bollingerLower' : IDL.Float64,
  'bollingerUpper' : IDL.Float64,
  'volumeTrend' : IDL.Float64,
  'rsi14' : IDL.Float64,
});
export const StockData = IDL.Record({
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'news' : IDL.Vec(NewsItem),
  'lastUpdated' : Time,
  'fundamentalData' : FundamentalData,
  'historicalPrices' : IDL.Vec(PriceData),
  'recommendation' : Recommendation,
  'technicalIndicators' : TechnicalIndicators,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAllRecommendations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Recommendation))],
      ['query'],
    ),
  'getAllStockTickers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFundamentalData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FundamentalData)],
      ['query'],
    ),
  'getHistoricalPrices' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(PriceData))],
      ['query'],
    ),
  'getNews' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(NewsItem))], ['query']),
  'getRecommendationV2' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Recommendation)],
      ['query'],
    ),
  'getStock' : IDL.Func([IDL.Text], [IDL.Opt(StockData)], ['query']),
  'getTechnicalIndicators' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TechnicalIndicators)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Recommendation = IDL.Record({
    'confidenceScore' : IDL.Nat,
    'signal' : IDL.Text,
  });
  const FundamentalData = IDL.Record({
    'eps' : IDL.Float64,
    'peRatio' : IDL.Float64,
    'marketCap' : IDL.Nat,
    'debtToEquity' : IDL.Float64,
    'revenueGrowth' : IDL.Float64,
    'dividendYield' : IDL.Float64,
  });
  const Time = IDL.Int;
  const PriceData = IDL.Record({
    'low' : IDL.Float64,
    'date' : Time,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Nat,
  });
  const NewsItem = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'source' : IDL.Text,
    'impactScore' : IDL.Nat,
    'sentiment' : IDL.Text,
    'timestamp' : Time,
  });
  const TechnicalIndicators = IDL.Record({
    'ma20' : IDL.Float64,
    'ma50' : IDL.Float64,
    'macd' : IDL.Float64,
    'bollingerLower' : IDL.Float64,
    'bollingerUpper' : IDL.Float64,
    'volumeTrend' : IDL.Float64,
    'rsi14' : IDL.Float64,
  });
  const StockData = IDL.Record({
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'news' : IDL.Vec(NewsItem),
    'lastUpdated' : Time,
    'fundamentalData' : FundamentalData,
    'historicalPrices' : IDL.Vec(PriceData),
    'recommendation' : Recommendation,
    'technicalIndicators' : TechnicalIndicators,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAllRecommendations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Recommendation))],
        ['query'],
      ),
    'getAllStockTickers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFundamentalData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FundamentalData)],
        ['query'],
      ),
    'getHistoricalPrices' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(PriceData))],
        ['query'],
      ),
    'getNews' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(NewsItem))], ['query']),
    'getRecommendationV2' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Recommendation)],
        ['query'],
      ),
    'getStock' : IDL.Func([IDL.Text], [IDL.Opt(StockData)], ['query']),
    'getTechnicalIndicators' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TechnicalIndicators)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };